services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: budget_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Host=db;Port=5432;Database=budget_app;Username=postgresql;Password=jagvillanvändaettbättrelösen
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.2}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend_react:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8080/api
        - VITE_BASE_PATH=/
    container_name: budget_frontend_react
    ports:
      - "3002:80"
    depends_on:
      - api
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: budget_db
    environment:
      POSTGRES_DB: budget_app
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: jagvillanvändaettbättrelösen
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresql -d budget_app" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: budget_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 12G

  ollama-init:
    image: ollama/ollama:latest
    container_name: ollama-init
    networks:
      - app-network
    depends_on:
      - ollama
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=ollama:11434
    entrypoint: /bin/sh
    command:
      - "-c"
      - |
        echo "Väntar på servern..."
        until ollama list > /dev/null 2>&1; do sleep 2; done

        echo "Laddar ner Llama 3.2 (för snabbhet)..."
        ollama pull llama3.2

        echo "Laddar ner Gemma 4 (för kvalitet)..."
        ollama pull gemma4:e4b

        echo "Alla modeller är redo!"
    restart: "no"

networks:
  app-network:
    driver: bridge
  traefik-net:
    external: true

volumes:
  db-data:
  pgadmin-data:
  ollama_data:
